export const state = {
  storyStarted: false,
  currentScrollingPosition: 0,
  scenes: [],
  transitions: [],
  duringTransition: false,
  currentTransitionStartingPage: -1,
  currentSceneCode: -1,
  mirrorImg: null,
  chapter2TitleImg: null,
  chapter2MapImg: null,
  posterImg: null,
  faceMesh: null,
  video: null,
  faces: [],
};
